### ISSUE TITLE
Doesnt seem to work with mLab URL

### ISSUE THREAD

**Issue by shivkanthb** [mvaragnat/botkit-express-demo#4]
For some reason theres a mongo Auth Error when the mongouri  is replaced with a mLab db string.

**Comment by mvaragnat** [comment]
have you solved your problem?

**Comment by shivkanthb** [comment]
Yes. I switched to mongoose from monk. Works fine now :)
Thanks!
On Jun 1, 2016, at 8:56 AM, Matthieu Varagnat <notifications@github.com<mailto:notifications@github.com>> wrote:

have you solved your problem?

**Comment by fdile** [comment]
Hi, I'm pretty new to Botkit. 
I can't manage to make the botkit interactive buttons work with your demo on heroku.
Did you deployed this on heroku?

**Comment by mvaragnat** [comment]
Yes, indeed. Can you perhaps open a new issue for your question?
